### ISSUE TITLE
REST api error message when creating a new deep link

### ISSUE THREAD

**Issue by yacinbenhamida** [BranchMetrics/Branch-Public-API#50]
Hey there,

- i have detected a new issue with the branch REST API (api2.branch.io/v1/url), when sending the showcased JSON payload in the branch io official documentation to the api to create a deep link  i get the following error message : 

`{
    "error": {
        "code": 400,
        "message": "The following key(s) are restricted link data keys. Please remove them or replace with valid link data key(s): ~creation_source, ~stage, +match_guaranteed, +is_first_session, +click_timestamp"
    }
}`

- the provided payload is identical to the one mentionned here : https://help.branch.io/developers-hub/docs/deep-linking-api

**POST** `https://api2.branch.io/v1/url`
`{
          "branch_key":"key_test_YOURKEY",
          "randomized_bundle_token": "427469360685348303",
          "link": "https://example.app.link?%24randomized_bundle_token=427469360685348303",
          "session_id": "429691081177874743",
          "data": {
            "$canonical_identifier": "item/1503684554354.28",
            "$canonical_url": "https://example.com/home?utm_campaign=test&deeplink=value",
            "$desktop_url": "http://example.com/home",
            "$randomized_bundle_token": "427469360685348303",
            "$og_description": "My Content Description",
            "$og_image_url": "http://lorempixel.com/200/200/",
            "$og_title": "46D6D28E-0390-40E4-A856-BD74F34D24C8",
            "$publicly_indexable": 1,
            "+click_timestamp": 1503684563,
            "+clicked_branch_link": true,
            "+is_first_session": false,
            "+match_guaranteed": true,
            "custom": "blue",
            "random": "FE848A5B-78F7-42EC-A253-9F795FE91692",
            "added": "1503684554354.33",
            "~campaign": "new launch",
            "~channel": "facebook",
            "~creation_source": 3,
            "~feature": "sharing",
            "~id": 429691043152332059,
            "~referring_link": "https://example.app.link/X7OsnWv9TF",
            "~stage": "new person",
            "~tags": [
              "one",
              "two"
            ]
          }
        }`
        

**did anyone face this issue recently also with the api ?**

Thank you.

**Comment by mochadwi** [comment]
happened in our ends as well:

```
error : {"error": "rpc error: code = Code(400) desc = {\"error\":{\"code\":400,\"message\":\"The following key(s) are restricted link data keys. Please remove them or replace with valid link data key(s): ~creation_source\"}}"}
```

Updates:

after removing the `~creation_source` attributes from the payload request, works for us

**Comment by yacinbenhamida** [comment]
Yes but we need that attribute on our end, we can't just remove stuff like that. hope this gets addressed

**Comment by jleebranch** [comment]
This has been fixed as of this morning.
